### ISSUE TITLE
关于我 - 奥斯特诺夫司机's Blog

### ISSUE THREAD

**Issue by Ostrovsky2056** [Ostrovsky2056/Ostrovsky2056.github.io#1]
https://ostrovsky2056.github.io/about/

**Comment by Ostrovsky2056** [comment]
# test

**Comment by Cwander-cc** [comment]
这是啥！这是啥！字体大小都不对！都是bug！
                                                                      —— 刘学凯

**Comment by Lxk-Kallen** [comment]
这是啥！这是啥！字体大小都不对！都是bug！
—— 常成

**Comment by Cwander-cc** [comment]
就你有头像是吧！
